### ISSUE TITLE
Layout control

### ISSUE THREAD

**Issue by MariaCobretti** [akovac35/BlazorMergely#1]
how can I control the size and styling of the component?

**Comment by akovac35** [comment]
Hi,

You may do as follows if using bootstrap:

<div class="form-row">
	<div class="col" style="height:400px">
		<BlazorMergelyComponent @ref="BlazorMergelyComponentInstance"
***@***.*** />
	</div>
</div>

Otherwise, the relevant div class is “mergely-resizer”, you can apply
the styling to it.

**Comment by MariaCobretti** [comment]
thx
